import { getUserFromHeaders } from '@/lib/auth';
import { streamWorkflowChat, manageContext } from '@/lib/claude';
import { getRawMcpTools, type RawMcpTool } from '@/lib/mcp-bridge';
import {
  createConversation,
  appendMessages,
  getConversation,
  logAnalyticsEvent,
  type DisplayMessage,
} from '@/lib/firestore';
import type { AnalyticsEvent, AssistantMode, InitiativePrefill } from '@/lib/types';
import {
  getDepartment,
  getDepartmentCredentialsMarkdown,
  DEFAULT_DEPARTMENT,
  type DepartmentConfig,
} from '@/lib/departments';
import type { ChatEvent } from '@/lib/types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** Build an XML context block with department-scoped credentials and rules. */
function buildDepartmentContext(dept: DepartmentConfig, mode: AssistantMode = 'builder'): string {
  const systems = dept.specs.join(', ');

  if (mode === 'data') {
    // Data consultant mode: system list + rules only, no credential IDs
    return `<department_context department="${dept.displayName}">
You are assisting a ${dept.displayName} team member. Available data sources for this department: ${systems}.
${dept.promptRules ?? ''}
</department_context>`;
  }

  // Builder mode: full credentials + rules
  const credTable = getDepartmentCredentialsMarkdown(dept);
  return `<department_context department="${dept.displayName}">
You are assisting a ${dept.displayName} team member. Scope your responses to these systems: ${systems}.

Available credentials for this department:
${credTable}

Use ONLY the credentials listed above when building workflow JSON.
${dept.promptRules ?? ''}
</department_context>`;
}

/**
 * Build an XML <initiative_context> block from a Hub-supplied prefill payload.
 * Prepended BEFORE <department_context> in the first user message because the
 * initiative is the higher-level frame for the whole conversation.
 *
 * Two modes:
 *   - building : restate the initiative + ask Claude to translate it to a workflow
 *   - planning : interview the user about field gaps; propose form-population JSON at end
 */
function buildInitiativeContext(prefill: InitiativePrefill): string {
  const m = prefill.initiative_metadata;
  const lines = [
    `Initiative ID: ${prefill.initiative_id}`,
    `Title: ${m.title}`,
    m.improvement_kpi ? `KPI: ${m.improvement_kpi}` : null,
    m.business_justification ? `Business justification: ${m.business_justification}` : null,
    m.current_state ? `Current state: ${m.current_state}` : null,
    m.data_sources ? `Data sources mentioned: ${m.data_sources}` : null,
    m.department ? `Department: ${m.department}` : null,
    `Hub: ${m.hub_url}`,
  ]
    .filter(Boolean)
    .join('\n');

  const draftBlock = prefill.initiative_draft
    ? `\n\nDraft (so far):\n${JSON.stringify(prefill.initiative_draft, null, 2)}`
    : '';

  if (prefill.mode === 'planning') {
    return `<initiative_context mode="planning" initiative_id="${prefill.initiative_id}">
${lines}${draftBlock}

You are in PLANNING mode. The user is drafting this initiative in the Hub and clicked
"Plan with AI" to refine it. Your job:
  1. Acknowledge the initiative by name in your first reply.
  2. Identify which fields are sparse or missing (KPI? business justification? current
     state? baseline labor cost?). Interview the user one or two questions at a time,
     prioritising the highest-impact gaps.
  3. After 3-5 turns of refinement, propose a JSON block with the form-fill values:
       \`\`\`json
       { "improvement_kpi": "...", "business_justification": "...", "current_state": "...",
         "current_process_minutes_per_run": <number>, "current_process_runs_per_month": <number>,
         "current_process_people_count": <number> }
       \`\`\`
  4. Tell the user they can copy these into the Hub form (Session 2 will auto-populate).

Do NOT generate workflow JSON in planning mode. Workflow building happens in a
separate session after the initiative is saved.
</initiative_context>`;
  }

  // building mode
  return `<initiative_context mode="building" initiative_id="${prefill.initiative_id}">
${lines}

You are in BUILDING mode. The user clicked "Generate workflow with AI" on this
saved initiative. Your job:
  1. Acknowledge the initiative by name in your first reply.
  2. Restate the requirements you infer from the metadata above in your own words —
     the trigger, data sources, transformations, destinations, and success metric.
  3. Ask only the clarifying questions that are NOT already answered by the metadata.
  4. Proceed with the standard workflow build flow once aligned.

When you emit the workflow JSON, the header sticky note MUST include three extra
lines after the purpose (per the system prompt's <sticky_notes> rule):
    **Initiative:** ${m.title}
    **Generated by:** @{handle} on {YYYY-MM-DD}
    **Hub:** ${m.hub_url}
</initiative_context>`;
}

export async function POST(req: Request): Promise<Response> {
  const user = getUserFromHeaders(req.headers);
  if (!user) {
    return new Response('Unauthorized', { status: 401 });
  }

  let body: {
    message?: string;
    conversationId?: string;
    departmentId?: string;
    mode?: AssistantMode;
    file?: { name: string; content: string; encoding: 'text' | 'base64'; mediaType: string };
    prefill?: InitiativePrefill;
  };
  try {
    body = (await req.json()) as typeof body;
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  const { message, conversationId: existingConvId, file, prefill } = body;
  if (!message?.trim()) {
    return new Response('message is required', { status: 400 });
  }

  // Resolve department and mode
  let departmentId = body.departmentId ?? DEFAULT_DEPARTMENT;
  let mode: AssistantMode = body.mode ?? 'builder';

  // Load or create the conversation
  let conversationId = existingConvId;
  let history: DisplayMessage[] = [];

  if (conversationId) {
    const conv = await getConversation(user.email, conversationId);
    if (conv) {
      history = conv.messages;
      // Use the conversation's stored department and mode (not the request's)
      if (conv.departmentId) {
        departmentId = conv.departmentId;
      }
      if (conv.mode) {
        mode = conv.mode;
      }
    } else {
      conversationId = undefined;
    }
  }

  // If a Hub-supplied prefill scopes the conversation to an initiative AND its
  // department maps to a known chat-ui dept id, lock the conversation to that dept
  // before persisting (so the conversation doc records the right value).
  const prefillDeptId = prefill?.initiative_metadata?.department_id;
  if (!existingConvId && prefillDeptId) {
    const mapped = getDepartment(prefillDeptId);
    if (mapped) {
      departmentId = prefillDeptId;
    }
  }

  if (!conversationId) {
    conversationId = await createConversation(
      user.email,
      message,
      departmentId,
      mode,
      prefill?.initiative_id,
      prefill?.mode,
    );
  }

  const convId = conversationId; // narrowed — always defined from here on

  // Build department context prefix for the first message of new conversations
  const dept = getDepartment(departmentId);
  let enrichedMessage = message;
  if (!existingConvId && dept) {
    const contextPrefix = buildDepartmentContext(dept, mode);
    // Initiative context goes ABOVE department context — initiative is the higher-level frame.
    const initiativePrefix = prefill ? `${buildInitiativeContext(prefill)}\n\n` : '';
    enrichedMessage = `${initiativePrefix}${contextPrefix}\n\n${message}`;
  }

  // Fire-and-forget: tell the Hub a conversation has started against this
  // initiative so it shows up in the IdeaDetailModal "AI Sessions" panel.
  if (!existingConvId && prefill && process.env.HUB_CALLBACK_URL && process.env.HUB_CALLBACK_SECRET) {
    fetch(`${process.env.HUB_CALLBACK_URL}/n8n-conversation-callback`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Hub-Secret': process.env.HUB_CALLBACK_SECRET,
      },
      body: JSON.stringify({
        initiative_id: prefill.initiative_id,
        conversation_id: convId,
        mode: prefill.mode === 'planning' ? 'planning' : 'building',
        created_by: user.email,
      }),
    }).catch((err) => console.error('Hub conversation-callback failed:', err));
  }

  // Fetch n8n-mcp tools (cached)
  let rawTools: RawMcpTool[] = [];
  try {
    rawTools = await getRawMcpTools();
  } catch (err) {
    console.error('Failed to load MCP tools:', err);
  }

  // Apply context windowing for long conversations (>16 messages AND >80K tokens)
  const { messages: managedHistory, windowed } = await manageContext(history, mode);
  if (windowed) {
    console.log(`Context windowed: ${history.length} → ${managedHistory.length} messages`);
  }

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      function enqueue(event: ChatEvent & { conversationId?: string }) {
        controller.enqueue(
          encoder.encode(`data: ${JSON.stringify(event)}\n\n`)
        );
      }

      const modelChunks: string[] = [];
      const eventStream = streamWorkflowChat(managedHistory, enrichedMessage, rawTools, departmentId, file, mode);

      // Analytics tracking
      const startTime = Date.now();
      const toolCallNames: string[] = [];

      try {
        for await (const event of eventStream) {
          if (event.type === 'text_chunk') {
            modelChunks.push(event.text);
            enqueue(event);
          } else if (event.type === 'tool_call') {
            toolCallNames.push(event.name);
            enqueue(event);
          } else if (event.type === 'done') {
            // Persist the user turn + model response
            const userMsg: DisplayMessage = {
              role: 'user',
              content: message,
              timestamp: new Date().toISOString(),
            };
            const modelMsg: DisplayMessage = {
              role: 'model',
              content: modelChunks.join(''),
              timestamp: new Date().toISOString(),
              ...(event.toolSummary ? { toolContext: event.toolSummary } : {}),
            };

            try {
              const { messageLimitReached } = await appendMessages(user.email, convId, [userMsg, modelMsg]);
              if (messageLimitReached) {
                enqueue({ type: 'text_chunk', text: '\n\n> **Note:** This conversation has reached the 100-message limit. Older messages have been trimmed. Consider starting a new conversation for best results.' });
              }
            } catch (err) {
              console.error('Failed to persist messages:', err);
            }

            // Log analytics event with token usage (fire-and-forget)
            const usage = event.usage;
            const analyticsEvent: AnalyticsEvent = {
              userEmail: user.email,
              departmentId,
              mode,
              conversationId: convId,
              turnNumber: Math.floor(history.length / 2) + 1,
              sessionStartedAt: new Date(startTime).toISOString(),
              latencyMs: Date.now() - startTime,
              toolCallCount: toolCallNames.length,
              toolCallNames,
              skillsLoaded: toolCallNames.filter(n => n === 'get_n8n_skill'),
              specsLoaded: toolCallNames.filter(n => n === 'get_company_spec'),
              inputTokens: usage?.inputTokens,
              outputTokens: usage?.outputTokens,
              cacheReadTokens: usage?.cacheReadTokens,
              cacheWriteTokens: usage?.cacheWriteTokens,
              truncated: event.truncated,
              contextWindowed: windowed,
              createdAt: new Date().toISOString(),
            };
            logAnalyticsEvent(analyticsEvent).catch(console.error);

            enqueue({ type: 'done', conversationId: convId });
            controller.close();
            return;
          } else if (event.type === 'error') {
            enqueue(event);
            controller.close();
            return;
          }
        }
      } catch (err) {
        enqueue({ type: 'error', message: String(err) });
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    },
  });
}
